# Generated by Django 3.1.1 on 2020-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out of stock', 'out of stock'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=100, null=True),
        ),
    ]
