# Generated by Django 3.1.1 on 2020-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pornstar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornstar',
            name='linga',
            field=models.CharField(choices=[('lado', 'lado'), ('puti', 'puti')], max_length=100, null=True),
        ),
    ]
