# Generated by Django 3.1.1 on 2020-09-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pornstar', '0002_auto_20200917_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornstar',
            name='size',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
