# Generated by Django 3.1.1 on 2020-09-18 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pornstar', '0003_auto_20200917_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='video_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p')], max_length=100, null=True)),
                ('pornstar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pornstar.pornstar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pornstar.user')),
            ],
        ),
        migrations.AddField(
            model_name='pornstar',
            name='char',
            field=models.ManyToManyField(to='pornstar.category'),
        ),
    ]
