# Generated by Django 3.1.1 on 2020-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sweet_fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('raw', 'raw'), ('rippen', 'rippen')], max_length=100)),
            ],
        ),
    ]
